version: '3.8'

services:
  web:
    build: ./final_template
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./final_template/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.dev_env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db_dev_env

volumes:
  postgres_data: