version: '3.8'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/onlinecourse_app/staticfiles
      - media_volume:/home/onlinecourse_app/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build: ./final_template
    command: gunicorn myproject.wsgi -b :8000
    volumes:
      - static_volume:/home/onlinecourse_app/staticfiles
      - media_volume:/home/onlinecourse_app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.dev_env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.db_prod_env

volumes:
  postgres_data:
  static_volume:
  media_volume: